### APP ###

app_categorical_features = ['NAME_CONTRACT_TYPE', # đã loại trừ các cat_col nhị phân
                         'NAME_TYPE_SUITE',
                         'NAME_INCOME_TYPE',
                         'NAME_EDUCATION_TYPE',
                         'NAME_FAMILY_STATUS',
                         'NAME_HOUSING_TYPE',
                         'OCCUPATION_TYPE',
                         'WEEKDAY_APPR_PROCESS_START',
                         'ORGANIZATION_TYPE',
                         'FONDKAPREMONT_MODE',
                         'HOUSETYPE_MODE',
                         'WALLSMATERIAL_MODE',
                         ]

money_cols = ["AMT_INCOME_TOTAL", "AMT_CREDIT",
              "AMT_ANNUITY", "AMT_GOODS_PRICE"]
day_cols = ["DAYS_BIRTH", "DAYS_EMPLOYED", "DAYS_REGISTRATION",
            "DAYS_ID_PUBLISH", "DAYS_LAST_PHONE_CHANGE"]
cnt_cols = ["CNT_CHILDREN", "CNT_FAM_MEMBERS"]
ext_cols = ["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]
avg_cols = ['APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG',
            'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG']
mode_cols = ['APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE',
             'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'TOTALAREA_MODE']
medi_cols = ['APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI',
             'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI']
other_cols = ["REGION_POPULATION_RELATIVE",
              "OWN_CAR_AGE", "HOUR_APPR_PROCESS_START"]
social_cols = ["OBS_30_CNT_SOCIAL_CIRCLE", "DEF_30_CNT_SOCIAL_CIRCLE",
               "OBS_60_CNT_SOCIAL_CIRCLE", "DEF_60_CNT_SOCIAL_CIRCLE"]
req_bureau_cols = ['AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
                   'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']



# các cột dùng để tính toán với các bảng khác
use_cols = ['SK_ID_CURR', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
            'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'DAYS_LAST_PHONE_CHANGE']

rename_di = {
    'AMT_INCOME_TOTAL':       'app_AMT_INCOME_TOTAL',
    'AMT_CREDIT':             'app_AMT_CREDIT',
    'AMT_ANNUITY':            'app_AMT_ANNUITY',
    'AMT_GOODS_PRICE':        'app_AMT_GOODS_PRICE',

    'DAYS_BIRTH':             'app_DAYS_BIRTH',
    'DAYS_EMPLOYED':          'app_DAYS_EMPLOYED',
    'DAYS_REGISTRATION':      'app_DAYS_REGISTRATION',
    'DAYS_ID_PUBLISH':        'app_DAYS_ID_PUBLISH',
    'DAYS_LAST_PHONE_CHANGE': 'app_DAYS_LAST_PHONE_CHANGE',
}

app_money_cols = ['app_AMT_INCOME_TOTAL', 'app_AMT_CREDIT',
                  'app_AMT_ANNUITY', 'app_AMT_GOODS_PRICE']
app_day_cols = ['app_DAYS_BIRTH', 'app_DAYS_EMPLOYED',
                'app_DAYS_REGISTRATION', 'app_DAYS_ID_PUBLISH', 'app_DAYS_LAST_PHONE_CHANGE']